// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoynCHjRlfJQIuVmkielY3Q_fGsQAMBes',
    appId: '1:417023388555:web:3933869cee76544214dd8e',
    messagingSenderId: '417023388555',
    projectId: 'pregacare-b07de',
    authDomain: 'pregacare-b07de.firebaseapp.com',
    storageBucket: 'pregacare-b07de.firebasestorage.app',
    measurementId: 'G-QBGP06CX6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEsMtL43mj388d4qe2E8PZkw2FiRyHLqQ',
    appId: '1:417023388555:android:533e6319f770f68514dd8e',
    messagingSenderId: '417023388555',
    projectId: 'pregacare-b07de',
    storageBucket: 'pregacare-b07de.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoynCHjRlfJQIuVmkielY3Q_fGsQAMBes',
    appId: '1:417023388555:web:37905f2d5e19333814dd8e',
    messagingSenderId: '417023388555',
    projectId: 'pregacare-b07de',
    authDomain: 'pregacare-b07de.firebaseapp.com',
    storageBucket: 'pregacare-b07de.firebasestorage.app',
    measurementId: 'G-QQJZWY8PGH',
  );
}
